// Data Service Content

export interface HeroContent {
  headline: string;
  subheadline: string;
  valueProp: string;
  targetAudience: string;
}

export const heroContent: HeroContent = {
  headline: "The Executive Coach for Data Leaders",
  subheadline: "Building world-class data organizations through expert recruiting and leadership coaching.",
  valueProp: "I don't just fix your pipelines; I fix your organization. From hiring your first Head of Data to coaching your existing VP, I build the human engines that drive data success.",
  targetAudience: "For Non-technical Founders & Private Equity Firms."
}

export interface Service {
  title: string;
  description: string;
  audience: string;
}

export const services: Service[] = [
  {
    title: "Executive Coaching",
    description: "For VPs and Heads of Data: A strategic sounding board to help you navigate politics, prioritize ruthlessly, and lead with authority.",
    audience: "Series A - C"
  },
  {
    title: "Master Recruiting",
    description: "I own your critical hires. I source, screen, and close top 1% talent, leveraging a career's worth of network and technical vetting.",
    audience: "All Stages"
  },
  {
    title: "Organizational Design",
    description: "Structuring your data team for scale. I define roles, career ladders, and operating models that align with business value.",
    audience: "Seed - Series B"
  }
]

export interface ProblemSolved {
  problem: string;
  solution: string;
}

export const problemsSolved: ProblemSolved[] = [
  {
    problem: "The Infinite Search",
    solution: "You've had an open rec for 6 months. I fill it in 6 weeks with a candidate I've personally vetted."
  },
  {
    problem: "The Lonely Leader",
    solution: "Your Head of Data is burning out. I provide the mentorship and strategic support they need to thrive."
  },
  {
    problem: "Culture Clash",
    solution: "Your data team is siloed. I rebuild the bridge between data and the business through culture and process."
  }
]

export interface ImpactMetric {
  metric: string
  description: string
  year: string
  category: string
}

export const impactData: ImpactMetric[] = [
  {
    metric: "$4.2M",
    description: "New ARR generated by identifying and targeting high-LTV customer segments",
    year: "2024",
    category: "Revenue",
  },
  {
    metric: "40%",
    description: "Reduction in CAC through precise multi-touch attribution modeling",
    year: "2023",
    category: "Efficiency",
  },
  {
    metric: "Series B",
    description: "Led data due diligence and metric preparation for successful raise",
    year: "2023",
    category: "Capital",
  },
  {
    metric: "0 → 1",
    description: "Built the data culture and hiring roadmap for scale",
    year: "2020-2024",
    category: "Leadership",
  },
]

export interface ExpertiseArea {
  category: string
  skills: string[]
}

export const expertiseAreas: ExpertiseArea[] = [
  {
    category: "Executive Leadership",
    skills: ["Team Building & Culture", "Org Design", "Vendor Negotiation", "Board Relations"],
  },
  {
    category: "Talent Strategy",
    skills: ["Executive Search", "Technical Vetting", "Compensation Benchmarking", "Retention Strategy"],
  },
  {
    category: "Leadership Coaching",
    skills: ["Stakeholder Management", "Strategic Planning", "Communication", "Org Politics"],
  },
  {
    category: "Strategic Analytics",
    skills: ["Revenue Forecasting", "Business Logic Mapping", "KPI Definition", "Unit Economics"],
  },
]

export interface TimelineItem {
  year: string
  endYear?: string
  title: string
  organization: string
  type: "education" | "experience" | "certification" | "venture"
  current?: boolean
  description?: string
}

export const educationData: TimelineItem[] = [
  {
    year: "2016",
    title: "Lean Six Sigma Green Belt",
    organization: "Process Excellence Institute",
    type: "certification",
    description: "Process optimization and operational efficiency.",
  },
  {
    year: "2017",
    title: "Bachelor's Degree, Mathematics",
    organization: "University of South Florida",
    type: "education",
    description: "Foundation in statistical theory and mathematical modeling.",
  },
  {
    year: "2018",
    title: "IBM Data Science Professional",
    organization: "IBM",
    type: "certification",
    description: "Machine learning and data science certification.",
  },
  {
    year: "2021",
    title: "Executive Management Program",
    organization: "Harvard University",
    type: "education",
    description: "Strategic leadership and organizational management.",
  },
  {
    year: "2024",
    title: "MicroMasters, Data, Economics, and Policy",
    organization: "Massachusetts Institute of Technology",
    type: "education",
    description: "Advanced coursework in econometrics and causal inference.",
  },
]

export const professionalData: TimelineItem[] = [
  {
    year: "2014",
    title: "Principal",
    organization: "Viveiros Ventures",
    type: "venture",
    current: true,
    description: "Fractional data leadership and startup advisory.",
  },
  /*
    {
      year: "2016",
      endYear: "2017",
      title: "Data Science Research Intern",
      organization: "University of South Florida",
      type: "experience",
    },
  */
  /*
    {
      year: "2017",
      endYear: "2020",
      title: "Data Scientist",
      organization: "Disciplined Minds Tutoring",
      type: "experience",
      description: "Predictive modeling for student performance optimization.",
    },
  */
  {
    year: "2020",
    endYear: "2022",
    title: "BI Analyst (Data Science & Operations)",
    organization: "Tenth Avenue Commerce",
    type: "experience",
    description: "Built self-service analytics platform scaling to 150+ users.",
  },
  {
    year: "2022",
    title: "Advanced Analytics & BI Manager",
    organization: "Connected Dealer Services",
    type: "experience",
    current: true,
    description: "Leading enterprise data strategy and ML-powered financial analytics.",
  },
  {
    year: "2023",
    title: "Co-Founder",
    organization: "Trajectory Tutors",
    type: "venture",
    current: true,
    description: "Data-driven tutoring platform with AI-enhanced curriculum matching.",
  },
  {
    year: "2024",
    title: "Treasurer & Vice President",
    organization: "Trajectory Foundation",
    type: "venture",
    current: true,
    description: "Strategic financial oversight for educational nonprofit.",
  },
]

export interface Slide {
  title: string
  subtitle?: string
  content: string[]
  highlight?: string
  visual?: "chart" | "process" | "metrics" | "tech" | "financial"
}

export const strategySlides: Slide[] = [
  {
    title: "AI-Enhanced Financial Analytics Platform",
    subtitle: "Connected Dealer Services • 2022-2024",
    content: [
      "Challenge: Manual financial reporting across multiple revenue streams",
      "Fragmented data sources hindering real-time financial insights",
      "Need for predictive cash flow and revenue recognition automation"
    ],
    visual: "financial"
  },
  {
    title: "Strategic AI Architecture",
    subtitle: "End-to-End Financial Intelligence System",
    content: [
      "ML-powered revenue recognition with 99.2% accuracy",
      "Automated anomaly detection for financial transactions",
      "Predictive cash flow modeling using ensemble methods",
      "Real-time financial dashboard with AI-driven insights"
    ],
    visual: "process"
  },
  {
    title: "Technical Implementation",
    subtitle: "Modern Data Stack + AI/ML Pipeline",
    content: [
      "Snowflake data warehouse with dbt transformations",
      "Python + TensorFlow for predictive financial models",
      "Apache Airflow orchestrating ML workflows",
      "Looker dashboards with embedded ML predictions"
    ],
    visual: "tech"
  },
  {
    title: "Business Impact",
    subtitle: "Transformational Financial Operations",
    content: [
      "Reduced month-end close time from 15 days to 3 days",
      "99.2% accuracy in automated revenue recognition",
      "Identified $2.1M in revenue optimization opportunities",
      "Enabled real-time financial decision making for C-suite"
    ],
    highlight: "$2.1M revenue optimization",
    visual: "chart"
  },
  {
    title: "Strategic Outcomes",
    subtitle: "AI-First Financial Operations",
    content: [
      "Established foundation for scalable financial analytics",
      "Created competitive advantage through predictive insights",
      "Enabled data-driven financial strategy and planning",
      "Built reusable ML framework for future applications"
    ],
    visual: "metrics"
  }
]

export interface Endorsement {
  quote: string
  author: string
  title: string
  company: string
  year: string
  verified: boolean
}

export const endorsements: Endorsement[] = [
  {
    quote: "Transformed our fragmented data into a strategic asset. The predictive models identified $2M+ in revenue opportunities within the first quarter.",
    author: "Executive Leadership",
    title: "CEO",
    company: "Connected Dealer Services",
    year: "2024",
    verified: true
  },
  {
    quote: "A rare combination of engineering rigor and business acumen. Built the infrastructure that allowed us to scale from 10 to 150+ analytics users.",
    author: "Operations VP",
    title: "VP of Operations",
    company: "Tenth Avenue Commerce",
    year: "2022",
    verified: true
  },
  {
    quote: "Redefined our approach to data governance. We moved from reactive reporting to proactive, AI-driven decision making.",
    author: "Technical Stakeholder",
    title: "CTO",
    company: "Trajectory Tutors",
    year: "2023",
    verified: true
  }
]
