#!/bin/bash

# Hourly Execution Reminder Script
# Run this every hour to stay on track

echo "=========================================="
echo "⏰ HOURLY CHECK-IN - $(date '+%I:%M %p')"
echo "=========================================="
echo ""
echo "CURRENT GOALS:"
echo "  □ 50 emails sent today"
echo "  □ 20 LinkedIn connections"
echo "  □ 3 discovery calls booked"
echo "  □ $10k revenue goal"
echo ""
echo "LAST HOUR:"
echo "  Emails sent: ___ / 50"
echo "  Connections: ___ / 20"
echo ""
echo "THIS HOUR'S FOCUS:"
echo "  Send ___ more emails"
echo "  Make ___ more connections"
echo ""
echo "URGENCY CHECK:"
echo "  Every email = potential \$10k client"
echo "  Every hour without sending = \$0"
echo ""
echo "BLOCKERS?"
echo "  If yes, write it down: ________________"
echo "  Solution: Just send the next email"
echo ""
echo "SCORE LAST HOUR: ___ / 10"
echo ""
echo "NEXT HOUR: Send more emails. Don't stop."
echo "=========================================="
echo ""
read -p "Press Enter to continue sending..."
